### ISSUE TITLE
Typo in section 2.2

### ISSUE THREAD

**Issue by kayless-git** [18F/its70-fs-epermit-scale-up#11]
# Question/Comment on the Forest Service RFP

## Nic Wissman (kayless) TrussWorks, Inc. 
I am the Manager for government programs. I'm involved with all aspects of the acquisition process as well as delivery and some business operations tasks.

## Section of RFP documents
Typo in section 2.2

## Question/Comment
S/In order to assist the vendor in ~~fulfill~~ the deliverables/In order to assist the vendor in *fulfilling* the deliverables

**Comment by hannahkane** [comment]
Fixed. Thank you for filing!
