### ISSUE TITLE
Google Survey submission confirmation

### ISSUE THREAD

**Issue by osi-vohra** [18F/its70-fs-epermit-scale-up#26]
# Question/Comment on the Forest Service RFP

## Name and affiliation
Indu Vohra, Scrum Master, Optimal Solutions Inc.

## Section of RFP documents
{please be specific about the section of the RFP documents you have a question or comment about, if applicable}  

## Question/Comment
Could you please confirm receipt of our Google survey submission? Submitted March 4, 2018, 10:30 PM EST.

**Comment by randyhart** [comment]
Confirmed.
