### ISSUE TITLE
ads.18F.gov

### ISSUE THREAD

**Issue by kwehmueller** [18F/its70-fs-epermit-scale-up#44]
# Question/Comment on the Forest Service RFP

## Name and affiliation
Kevin Wehmueller, Business Development Strategist, Taoti Creative

## Section of RFP documents
8.2 Roles and responsibilities

## Question/Comment
The Roles and responsibilities link (https://ads.18f.gov/roles-and-responsibilities/) is broken. Please provide an updated link to the 18F Assisted Acquisition Roles and Responsibilities Page in the final RFP.

**Comment by hannahkane** [comment]
Just noting that the link was updated. Thanks for finding it!
